final List contectData = [
{
  "name":"Aayush",
  "group":"A",
  "no":"9834789350",
  "icon":"assets/icon/star.png",
  "contBackground": "assets/images/4.jpg",
},
{
  "name":"Balhaar",
  "group":"B",
  "no":"8036584299",
  "icon":"assets/icon/star.png",
  "contBackground": "assets/images/3.jpg",
},
{
  "name":"Chaitanya",
  "group":"C",
  "no":"7529849638",
  "icon":"assets/icon/star.png",
  "contBackground": "",

},
{
  "name":"Bakhshi",
  "group":"B",
  "no":"9487037648",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Bahadurjit",
  "group":"B",
  "no":"9485027489",
  "icon":"assets/icon/starfill.png",
  "contBackground": "",
},
{
  "name":"Charan",
  "group":"C",
  "no":"8497502746",
  "icon":"assets/icon/starfill.png",
  "contBackground": "assets/images/6.jpg",
},
{
  "name":"Dev",
  "group":"D",
  "no":"9578409743",
  "icon":"assets/icon/starfill.png",
  "contBackground": "",
},
{
  "name":"Dhruv",
  "group":"D",
  "no":"9876345678",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Ekalinga",
  "group":"E",
  "no":"8769467234",
  "icon":"assets/icon/starfill.png",
  "contBackground": "assets/images/5.jpg",
},
{
  "name":"Fariz",
  "group":"F",
  "no":"8769574839",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Fiyaz",
  "group":"F",
  "no":"9869853423",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Gaurav",
  "group":"G",
  "no":"9876789087",
  "icon":"assets/icon/star.png",
  "contBackground": "assets/images/4.jpg",
},
{
  "name":"Harshil",
  "group":"H",
  "no":"8760983452",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Jai",
  "group":"J",
  "no":"6785435678",
  "icon":"assets/icon/star.png",
  "contBackground": "",
},
{
  "name":"Lohit",
  "group":"L",
  "no":"9876789054",
  "icon":"assets/icon/starfill.png",
  "contBackground": "",
}
];